services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    restart: always
    ports:
      - 4000:4000
    env_file:
      - ./.env
    # volumes:
    #   - ./prisma:/app/prisma
    #   - ./src:/app/src
    #   - ./types:/app/types
    #   - ./.env:/app/.env
    depends_on:
      db:
        condition: service_healthy
# volumes:
#   postgres_data:
#     name: postgres_data
