
FROM node:lts-alpine

WORKDIR /app

COPY [ "package.json", "package-lock.json", "./" ]

ENV NODE_ENV=development
RUN npm ci

COPY . .

EXPOSE 4000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]